"""
Pydantic Models for Notion Audio Content Processor

Defines data structures for audio generation, metadata, and processing results.
"""

from enum import Enum
from pathlib import Path
from typing import List, Optional
import os
import re

from pydantic import BaseModel, Field, field_validator


class AudioContentStatus(str, Enum):
    """Status values for Audio Content Record in Notion."""
    
    NOT_STARTED = "Not started"
    READY_FOR_AUDIO = "Ready for Audio"
    AUDIO_COMPLETED = "Audio Completed"
    READY_FOR_PUBLISHING = "Ready for Publishing"
    PROCESSING = "Processing"
    COMPLETED = "Completed"
    FAILED = "Failed"


class ContentMetadata(BaseModel):
    """Metadata generated by LLM for audio content."""
    
    description: str = Field(
        ...,
        min_length=50,
        max_length=200,
        description="Concise content summary"
    )
    
    tags: List[str] = Field(
        ...,
        min_length=3,
        max_length=7,
        description="Hashtags for categorization"
    )
    
    @field_validator("tags")
    @classmethod
    def validate_tag_format(cls, tags: List[str]) -> List[str]:
        """Ensure tags follow #tag format with no spaces."""
        for tag in tags:
            if not re.match(r'^#[a-zA-Z0-9_]+$', tag):
                raise ValueError(
                    f"Tag '{tag}' must start with # and contain no spaces"
                )
        return tags
    
    def tags_as_string(self) -> str:
        """Format tags for Notion (space-separated)."""
        return " ".join(self.tags)


class ProcessingResult(BaseModel):
    """Result of processing a single Audio Content Record."""
    
    record_id: str
    record_name: str
    success: bool
    error: Optional[str] = None
    audio_path: Optional[Path] = None
    processing_time: float
    skipped: bool = False
    
    def __str__(self) -> str:
        """Human-readable summary."""
        if self.skipped:
            return f"⏭️  SKIPPED: {self.record_name} (unchanged)"
        if self.success:
            return f"✅ SUCCESS: {self.record_name} ({self.processing_time:.1f}s)"
        return f"❌ FAILED: {self.record_name} - {self.error}"


class BatchProcessingSummary(BaseModel):
    """Summary of entire batch processing run."""
    
    total_records: int
    successful: int
    failed: int
    skipped: int
    total_time: float
    results: List[ProcessingResult]
    
    @property
    def success_rate(self) -> float:
        """Calculate success rate (excluding skipped)."""
        processed = self.total_records - self.skipped
        if processed == 0:
            return 100.0
        return (self.successful / processed) * 100.0
    
    def meets_success_criteria(self) -> bool:
        """Check if meets SC-001: 95% success rate."""
        return self.success_rate >= 95.0


class AudioProcessorConfig(BaseModel):
    """Configuration for Notion Audio Processor."""
    
    # Notion configuration
    notion_api_key: str = Field(..., description="Notion API token")
    notion_audio_db_id: str = Field(
        default="302dd30aa93a8087be8dda41b3b4de9b",
        description="Audio Content database ID"
    )
    notion_voice_db_id: str = Field(..., description="Voice configuration database ID")
    
    # Storage configuration
    storage_path: Path = Field(..., description="Root path for audio storage")
    
    # ElevenLabs configuration
    elevenlabs_api_key: str = Field(..., description="ElevenLabs API key")
    default_voice_id: str = Field(..., description="Default voice for fallback")
    tts_model: str = Field(default="eleven_multilingual_v2", description="TTS model")
    audio_format: str = Field(default="mp3_44100_192", description="Audio format")
    
    # LLM configuration
    llm_model: str = Field(default="gpt-4o-mini", description="LLM for metadata")
    llm_api_key: str = Field(..., description="OpenAI/Anthropic API key")
    
    @field_validator("storage_path")
    @classmethod
    def validate_storage_path(cls, path: Path) -> Path:
        """Ensure storage path exists and is writable."""
        if not path.exists():
            path.mkdir(parents=True, exist_ok=True)
        if not path.is_dir():
            raise ValueError(f"Storage path is not a directory: {path}")
        return path
    
    @classmethod
    def from_env(cls) -> "AudioProcessorConfig":
        """Load configuration from environment variables."""
        return cls(
            notion_api_key=os.getenv("NOTION_API_KEY"),
            notion_audio_db_id=os.getenv("NOTION_AUDIO_DATABASE_ID"),
            notion_voice_db_id=os.getenv("NOTION_VOICE_DATABASE_ID"),
            storage_path=Path(os.getenv("HAVACHAT_KNOWLEDGE_PATH")),
            elevenlabs_api_key=os.getenv("ELEVENLABS_API_KEY"),
            default_voice_id=os.getenv("DEFAULT_VOICE_ID"),
            tts_model=os.getenv("TTS_MODEL", "eleven_multilingual_v2"),
            audio_format=os.getenv("AUDIO_FORMAT", "mp3_44100_192"),
            llm_model=os.getenv("LLM_MODEL", "gpt-4o-mini"),
            llm_api_key=os.getenv("OPENAI_API_KEY") or os.getenv("ANTHROPIC_API_KEY"),
        )
