"""
Pydantic Models for Notion Audio Content Processor

Defines data structures for audio generation, metadata, and processing results.
Used throughout the audio pipeline and the extended meditation video pipeline.
"""

from enum import Enum
from pathlib import Path
from typing import List, Literal, Optional
import os
import re

from pydantic import BaseModel, Field, field_validator, model_validator


class AudioContentStatus(str, Enum):
    """Status values for Audio Content Record in Notion.

    Each value maps to a Notion select option on the Audio Content database.
    The lifecycle order is:
    NOT_STARTED → READY_FOR_AUDIO → AUDIO_COMPLETED →
    READY_FOR_VIDEO → VIDEO_COMPLETED → READY_FOR_PUBLISHING →
    COMPLETED (or FAILED at any stage).
    """

    NOT_STARTED = "Not started"
    READY_FOR_AUDIO = "Ready for Audio"
    AUDIO_COMPLETED = "Audio Completed"
    READY_FOR_VIDEO = "Ready for Video"
    VIDEO_COMPLETED = "Video Completed"
    READY_FOR_PUBLISHING = "Ready for Publishing"
    PROCESSING = "Processing"
    COMPLETED = "Completed"
    FAILED = "Failed"


class ContentMetadata(BaseModel):
    """Metadata generated by LLM for audio content.

    Produced by the metadata-extraction step and written back to the
    corresponding Notion Audio Content record.
    """

    description: str = Field(
        ...,
        min_length=50,
        max_length=200,
        description="Concise content summary (50–200 characters)"
    )

    tags: List[str] = Field(
        ...,
        min_length=3,
        max_length=7,
        description="Hashtags for categorization (3–7 tags, each starting with #)"
    )

    @field_validator("tags")
    @classmethod
    def validate_tag_format(cls, tags: List[str]) -> List[str]:
        """Ensure tags follow #tag format with no spaces.

        Each tag must begin with ``#`` and contain only alphanumeric characters
        or underscores.  Raises ``ValueError`` on the first non-conforming tag.
        """
        for tag in tags:
            if not re.match(r'^#[a-zA-Z0-9_]+$', tag):
                raise ValueError(
                    f"Tag '{tag}' must start with # and contain no spaces"
                )
        return tags

    def tags_as_string(self) -> str:
        """Format tags for Notion (space-separated).

        Returns a single string such as ``#meditation #sleep #relaxation``
        suitable for pasting into a Notion text property.
        """
        return " ".join(self.tags)


class ProcessingResult(BaseModel):
    """Result of processing a single Audio Content Record.

    Captures success/failure, timing, and the path of any generated audio
    file so that a ``BatchProcessingSummary`` can aggregate outcomes.
    """

    record_id: str = Field(..., description="Notion page ID of the processed record")
    record_name: str = Field(..., description="Human-readable title of the record")
    success: bool = Field(..., description="True if processing completed without error")
    error: Optional[str] = Field(default=None, description="Error message if success is False")
    audio_path: Optional[Path] = Field(default=None, description="Path to the generated audio file")
    processing_time: float = Field(..., description="Wall-clock seconds taken to process the record")
    skipped: bool = Field(default=False, description="True if the record was unchanged since last run")

    def __str__(self) -> str:
        """Human-readable summary of this result.

        Returns a single line prefixed with a status indicator:
        - Skipped records show ``SKIPPED``
        - Successful records show ``SUCCESS`` with elapsed time
        - Failed records show ``FAILED`` with the error message
        """
        if self.skipped:
            return f"⏭️  SKIPPED: {self.record_name} (unchanged)"
        if self.success:
            return f"✅ SUCCESS: {self.record_name} ({self.processing_time:.1f}s)"
        return f"❌ FAILED: {self.record_name} - {self.error}"


class BatchProcessingSummary(BaseModel):
    """Summary of entire batch processing run.

    Aggregates individual ``ProcessingResult`` objects and exposes
    computed properties for reporting and acceptance-criteria checks.
    """

    total_records: int = Field(..., description="Total number of records attempted (including skipped)")
    successful: int = Field(..., description="Number of records that completed successfully")
    failed: int = Field(..., description="Number of records that failed")
    skipped: int = Field(..., description="Number of records skipped due to no change")
    total_time: float = Field(..., description="Total wall-clock seconds for the batch run")
    results: List[ProcessingResult] = Field(..., description="Per-record results in processing order")

    @property
    def success_rate(self) -> float:
        """Calculate success rate (excluding skipped).

        Returns a percentage in the range ``[0.0, 100.0]``.  If no records
        were actually processed (all skipped) the rate is reported as
        ``100.0`` to avoid division by zero.
        """
        processed = self.total_records - self.skipped
        if processed == 0:
            return 100.0
        return (self.successful / processed) * 100.0

    def meets_success_criteria(self) -> bool:
        """Check if meets SC-001: 95% success rate.

        Returns ``True`` when ``success_rate >= 95.0``, the threshold
        defined in acceptance criterion SC-001.
        """
        return self.success_rate >= 95.0


class AudioProcessorConfig(BaseModel):
    """Configuration for Notion Audio Processor.

    Centralises all runtime configuration for the audio pipeline and the
    extended meditation video pipeline.  The preferred way to construct
    this model in production is via ``from_env()``.
    """

    # Notion configuration
    notion_api_key: str = Field(..., description="Notion API token")
    notion_audio_db_id: str = Field(
        default="302dd30aa93a8087be8dda41b3b4de9b",
        description="Audio Content database ID"
    )
    notion_voice_db_id: str = Field(..., description="Voice configuration database ID")

    # Storage configuration
    storage_path: Path = Field(..., description="Root path for audio storage")

    # ElevenLabs configuration
    elevenlabs_api_key: str = Field(..., description="ElevenLabs API key")
    default_voice_id: str = Field(
        default="7AvtJrjTNyBhBxEvNPIZ",
        description="ElevenLabs Rhythm voice — default for meditation audio generation"
    )
    tts_model: str = Field(default="eleven_multilingual_v2", description="TTS model identifier")
    audio_format: str = Field(default="mp3_44100_192", description="Audio output format string (codec_samplerate_bitrate)")

    # LLM configuration
    llm_model: str = Field(default="gpt-4o-mini", description="LLM model identifier used for metadata generation")
    llm_api_key: str = Field(..., description="OpenAI/Anthropic API key")

    # Video pipeline configuration
    image_backend: Literal["google", "runpod"] = Field(
        default="google",
        description="Backend used for background image generation (google=Gemini, runpod=Flux/SDXL)"
    )
    image_quality: Literal["nano", "pro"] = Field(
        default="nano",
        description="Image generation quality tier (nano=fast/cheap, pro=higher quality)"
    )
    ffmpeg_path: str = Field(
        default="ffmpeg",
        description="Path or command name for the ffmpeg binary used in video composition"
    )
    video_output_path: Optional[Path] = Field(
        default=None,
        description="Output directory for composed video files; defaults to storage_path/videos"
    )
    produce_shorts: bool = Field(
        default=False,
        description="When True, also produce a vertical 9:16 Shorts variant alongside the main video"
    )
    enable_karaoke: bool = Field(
        default=False,
        description="When True, burn word-level karaoke subtitles into the composed video"
    )

    @model_validator(mode="after")
    def _set_video_output_path(self) -> "AudioProcessorConfig":
        """Derive video_output_path from storage_path when not explicitly set.

        If ``video_output_path`` is ``None`` after field validation, it is
        set to ``storage_path / "videos"`` so callers never need to handle
        ``None`` after construction.
        """
        if self.video_output_path is None:
            self.video_output_path = self.storage_path / "videos"
        return self

    @field_validator("storage_path")
    @classmethod
    def validate_storage_path(cls, path: Path) -> Path:
        """Ensure storage path exists and is writable.

        Creates the directory (including any missing parents) if it does not
        already exist.  Raises ``ValueError`` if the resolved path is not a
        directory.
        """
        if not path.exists():
            path.mkdir(parents=True, exist_ok=True)
        if not path.is_dir():
            raise ValueError(f"Storage path is not a directory: {path}")
        return path

    @classmethod
    def from_env(cls) -> "AudioProcessorConfig":
        """Load configuration from environment variables.

        Reads the following variables (all required unless a default is noted):

        - ``NOTION_API_KEY``
        - ``NOTION_AUDIO_DATABASE_ID``
        - ``NOTION_VOICE_DATABASE_ID``
        - ``HAVACHAT_KNOWLEDGE_PATH``
        - ``ELEVENLABS_API_KEY``
        - ``DEFAULT_VOICE_ID`` (default: ``7AvtJrjTNyBhBxEvNPIZ``)
        - ``TTS_MODEL`` (default: ``eleven_multilingual_v2``)
        - ``AUDIO_FORMAT`` (default: ``mp3_44100_192``)
        - ``LLM_MODEL`` (default: ``gpt-4o-mini``)
        - ``OPENAI_API_KEY`` or ``ANTHROPIC_API_KEY``
        - ``IMAGE_BACKEND`` (default: ``google``)
        - ``IMAGE_QUALITY`` (default: ``nano``)
        - ``FFMPEG_PATH`` (default: ``ffmpeg``)
        - ``PRODUCE_SHORTS`` — ``"true"`` or ``"1"`` enables (default: off)
        - ``ENABLE_KARAOKE`` — ``"true"`` or ``"1"`` enables (default: off)
        """

        def _parse_bool(value: Optional[str]) -> bool:
            return (value or "").strip().lower() in ("true", "1")

        return cls(
            notion_api_key=os.getenv("NOTION_API_KEY"),
            notion_audio_db_id=os.getenv("NOTION_AUDIO_DATABASE_ID"),
            notion_voice_db_id=os.getenv("NOTION_VOICE_DATABASE_ID"),
            storage_path=Path(os.getenv("HAVACHAT_KNOWLEDGE_PATH")),
            elevenlabs_api_key=os.getenv("ELEVENLABS_API_KEY"),
            default_voice_id=os.getenv("DEFAULT_VOICE_ID", "7AvtJrjTNyBhBxEvNPIZ"),
            tts_model=os.getenv("TTS_MODEL", "eleven_multilingual_v2"),
            audio_format=os.getenv("AUDIO_FORMAT", "mp3_44100_192"),
            llm_model=os.getenv("LLM_MODEL", "gpt-4o-mini"),
            llm_api_key=os.getenv("OPENAI_API_KEY") or os.getenv("ANTHROPIC_API_KEY"),
            image_backend=os.getenv("IMAGE_BACKEND", "google"),
            image_quality=os.getenv("IMAGE_QUALITY", "nano"),
            ffmpeg_path=os.getenv("FFMPEG_PATH", "ffmpeg"),
            produce_shorts=_parse_bool(os.getenv("PRODUCE_SHORTS")),
            enable_karaoke=_parse_bool(os.getenv("ENABLE_KARAOKE")),
        )
